### understanding

You're absolutely right, and I apologize for the confusion earlier. Let's walk through the correct gradient descent formulas and final understanding based on your explanation.

Cost Function (J)
The cost function combines the reconstruction error (mean squared error) and regularization to minimize the difference between the predicted and actual ratings. Here's the updated version, considering your specifications:

𝐽
(
𝑋
,
𝑊
,
𝑏
)
=
1
2
∑
𝑖
=
1
𝑚
∑
𝑗
=
1
𝑛
𝑀
𝑖
𝑗
(
(
𝑊
𝑗
⋅
𝑋
𝑖
+
𝑏
𝑗
−
𝑌
𝑖
𝑗
)
2
)
+
𝜆
2
∑
𝑖
=
1
𝑚
∑
𝑘
=
1
𝐾
𝑋
𝑖
𝑘
2
+
𝜆
2
∑
𝑗
=
1
𝑛
∑
𝑘
=
1
𝐾
𝑊
𝑗
𝑘
2
+
𝜆
2
∑
𝑗
=
1
𝑛
𝑏
𝑗
2
J(X,W,b)= 
2
1
​
  
i=1
∑
m
​
  
j=1
∑
n
​
 M 
ij
​
 ((W 
j
​
 ⋅X 
i
​
 +b 
j
​
 −Y 
ij
​
 ) 
2
 )+ 
2
λ
​
  
i=1
∑
m
​
  
k=1
∑
K
​
 X 
ik
2
​
 + 
2
λ
​
  
j=1
∑
n
​
  
k=1
∑
K
​
 W 
jk
2
​
 + 
2
λ
​
  
j=1
∑
n
​
 b 
j
2
​
 
Where:

𝑌
𝑖
𝑗
Y 
ij
​
  is the rating given by user 
𝑗
j to movie 
𝑖
i,
𝑀
𝑖
𝑗
M 
ij
​
  is a binary mask indicating whether a rating exists for that user and movie pair (1 if rated, 0 if not),
𝑊
𝑗
W 
j
​
  is the feature vector for the 
𝑗
j-th user,
𝑋
𝑖
X 
i
​
  is the feature vector for the 
𝑖
i-th movie,
𝑏
𝑗
b 
j
​
  is the bias term for user 
𝑗
j,
𝜆
λ is the regularization parameter.
Gradient Descent Update Rules
Now, based on your updated logic, the gradient descent update formulas are as follows:

For 
𝑋
[
𝑖
,
𝑘
]
X[i,k] (movie features):
𝑋
[
𝑖
,
𝑘
]
:
=
𝑋
[
𝑖
,
𝑘
]
−
𝛼
⋅
∂
𝐽
∂
𝑋
[
𝑖
,
𝑘
]
X[i,k]:=X[i,k]−α⋅ 
∂X[i,k]
∂J
​
 
The gradient 
∂
𝐽
∂
𝑋
[
𝑖
,
𝑘
]
∂X[i,k]
∂J
​
  is:

∂
𝐽
∂
𝑋
[
𝑖
,
𝑘
]
=
∑
𝑗
=
1
𝑛
𝑀
[
𝑖
,
𝑗
]
(
(
𝑊
𝑗
⋅
𝑋
𝑖
+
𝑏
𝑗
−
𝑌
𝑖
𝑗
)
)
⋅
𝑊
𝑗
𝑘
+
𝜆
𝑋
𝑖
𝑘
∂X[i,k]
∂J
​
 = 
j=1
∑
n
​
 M[i,j]((W 
j
​
 ⋅X 
i
​
 +b 
j
​
 −Y 
ij
​
 ))⋅W 
jk
​
 +λX 
ik
​
 
For 
𝑊
[
𝑗
,
𝑘
]
W[j,k] (user features):
𝑊
[
𝑗
,
𝑘
]
:
=
𝑊
[
𝑗
,
𝑘
]
−
𝛼
⋅
∂
𝐽
∂
𝑊
[
𝑗
,
𝑘
]
W[j,k]:=W[j,k]−α⋅ 
∂W[j,k]
∂J
​
 
The gradient 
∂
𝐽
∂
𝑊
[
𝑗
,
𝑘
]
∂W[j,k]
∂J
​
  is:

∂
𝐽
∂
𝑊
[
𝑗
,
𝑘
]
=
∑
𝑖
=
1
𝑚
𝑀
[
𝑖
,
𝑗
]
(
(
𝑊
𝑗
⋅
𝑋
𝑖
+
𝑏
𝑗
−
𝑌
𝑖
𝑗
)
)
⋅
𝑋
𝑖
𝑘
+
𝜆
𝑊
𝑗
𝑘
∂W[j,k]
∂J
​
 = 
i=1
∑
m
​
 M[i,j]((W 
j
​
 ⋅X 
i
​
 +b 
j
​
 −Y 
ij
​
 ))⋅X 
ik
​
 +λW 
jk
​
 
For 
𝑏
[
𝑗
]
b[j] (user biases):
𝑏
[
𝑗
]
:
=
𝑏
[
𝑗
]
−
𝛼
⋅
∂
𝐽
∂
𝑏
[
𝑗
]
b[j]:=b[j]−α⋅ 
∂b[j]
∂J
​
 
The gradient 
∂
𝐽
∂
𝑏
[
𝑗
]
∂b[j]
∂J
​
  is:

∂
𝐽
∂
𝑏
[
𝑗
]
=
∑
𝑖
=
1
𝑚
𝑀
[
𝑖
,
𝑗
]
(
(
𝑊
𝑗
⋅
𝑋
𝑖
+
𝑏
𝑗
−
𝑌
𝑖
𝑗
)
)
∂b[j]
∂J
​
 = 
i=1
∑
m
​
 M[i,j]((W 
j
​
 ⋅X 
i
​
 +b 
j
​
 −Y 
ij
​
 ))
Algorithm Overview
Initialize: Initialize feature matrices 
𝑊
W, 
𝑋
X, and bias vector 
𝑏
b randomly (or with small random values).
For each iteration:
Compute the predicted ratings using the current feature matrices and biases.
Calculate the cost function with regularization.
Compute the gradients for 
𝑋
X, 
𝑊
W, and 
𝑏
b using the formulas above.
Update the parameters using the gradients and learning rate 
𝛼
α.
Convergence: Stop when the cost function reaches a minimum or after a predefined number of iterations.
Prediction:
The prediction for the rating of movie 
𝑖
i by user 
𝑗
j is computed as:

𝑌
𝑖
𝑗
=
𝑊
𝑗
⋅
𝑋
𝑖
+
𝑏
𝑗
Y 
ij
​
 =W 
j
​
 ⋅X 
i
​
 +b 
j
​
 
Regularization:
The regularization term helps prevent overfitting by adding penalties for large values of the weights, feature vectors, and biases.

### implementation

In [40]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import copy, math
# scaler = StandardScaler()
import tensorflow as tf
from tensorflow import keras
# from recsys_utils import *

In [41]:
column_names = ['User ID', 'Movie ID', 'Rating', 'Timestamp']
df = pd.read_csv('../../notes and data/ml-100k/u.data',sep='\t', names=column_names)
df = df.drop(columns=['Timestamp'])

In [3]:
# df[['Rating']] = scaler.fit_transform(df[['Rating']])

In [4]:
y = df.pivot(index='Movie ID', columns='User ID', values='Rating')
y = y.fillna(0)
y = np.array(y)
y

array([[5., 4., 0., ..., 5., 0., 0.],
       [3., 0., 0., ..., 0., 0., 5.],
       [4., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]:
M = (y != 0).astype(int)
print(y.shape,M.shape)

(1682, 943) (1682, 943)


In [42]:
# def costFn(x,y,w,b,lam):
#     cost = 0
#     pred = 0
#     reg = 0
#     for i in range(y.shape[0]):
#         for j in range(y.shape[1]):
#             if m[i][j] == 1:
#                 val = np.dot(w[j],x[i]) + b[j] - y[i][j]
#                 pred += (val**2)/2
                
#     for i in range(y.shape[0]):  # Regularization for X
#         reg += np.sum(x[i] ** 2)

#     for j in range(y.shape[1]):  # Regularization for W and b
#         reg += np.sum(w[j] ** 2) + b[j] ** 2

#     reg = (lam/2)*reg

#     cost = pred + reg  # Divide by 2m for proper scaling
#     return cost


def costFn(X, Y,W, b,m, lam):
    
    # nm, nu = Y.shape
    # J = 0
    # ### START CODE HERE ###  
    # for j in range(nu):
    #     w = W[j,:]
    #     b_j = b[0,j]
    #     for i in range(nm):
    #         x = X[i,:]
    #         y = Y[i,j]
    #         r = m[i,j]
    #         J += r * np.square((np.dot(w,x) + b_j - y ))
    # J += (lam) * (np.sum(np.square(W)) + np.sum(np.square(X)))
    # J = J/2
    # ### END CODE HERE ### 

    # return J
    j = (tf.linalg.matmul(X, tf.transpose(W)) + b - Y)*m
    J = 0.5 * tf.reduce_sum(j**2) + (lam/2) * (tf.reduce_sum(X**2) + tf.reduce_sum(W**2))
    return J


In [7]:
def gradientfn(x,y,w,b,m,lam):
    djx = np.zeros_like(x)
    djw = np.zeros_like(w)
    djb = np.zeros_like(b)
    for i in range(y.shape[0]):
        for k in range(len(x[i])):
            for j in range(y.shape[1]):
                if m[i][j] == 1:
                    val = np.dot(w[j],x[i]) + b[0,j] - y[i][j]
                    djx[i][k] += val*w[j][k]
            djx[i][k] += lam*x[i][k]
            
    for j in range(y.shape[1]):
        for k in range(len(w[j])):
            for i in range(y.shape[0]):
                if m[i][j] == 1:
                    val = np.dot(w[j],x[i]) + b[0,j] - y[i][j]
                    djw[j][k] += val*x[i][k]
            djw[j][k] += lam*w[j][k]
            
    for j in range(y.shape[1]):
        for i in range(y.shape[0]):
            if m[i][j] == 1:
                val = np.dot(w[j],x[i]) + b[0,j] - y[i][j]
                djb[0,j] += val    
    
    return djw, djb ,djx 

In [8]:
def gradientDecent(x,y,w_in,b_in,alpha,iters,lam,m):
    # x = copy.deepcopy(x)
    # w = copy.deepcopy(w_in) #avoid modifying global w within function
    # b = copy.deepcopy(b_in)
    # for i in range(iters):
    #     djw,djb,djx = gradientfn(x,y,w,b,m,lam)
    #     w = w - alpha*djw
    #     b = b - alpha*djb
    #     x = x - alpha*djx
    #     # if i % 100 == 0 and i > 0:
    #     #     alpha *= 0.9
    #     if i % math.ceil(iters / 10) == 0:
    #         cost = costFn(x,y,w,b,m,lam)
    #         print(f"Iteration {i:4d}: Cost {cost:.4f}")
    for iter in range(iters):
        with tf.GradientTape() as tape:
            # Compute the cost (forward pass included in costFn)
            cost_value = costFn(x, y, w_in, b_in, m, lam)
        
        # Compute gradients
        grads = tape.gradient(cost_value, [x, w_in, b_in])
        
        # Apply gradients to variables
        optimizer.apply_gradients(zip(grads, [x, w_in, b_in]))

        # Log periodically
        if iter % 20 == 0:
            print(f"Training loss at iteration {iter}: {cost_value.numpy():0.1f}")
    
    return w, b, x

In [10]:
def predict(xt, wt, bt):
    print(xt.shape,wt.shape,bt.shape)
    # predicted_ratings = np.dot(x, w.T) + b  # Matrix multiplication for all users and all movies
    predicted_ratings = np.matmul(xt.numpy(), np.transpose(wt.numpy())) + bt.numpy()
    return predicted_ratings

In [33]:
num_features = 100
num_movies, num_users = y.shape  # Total number of users (943)
subset_users = num_users # Number of users you want to use for faster processing
optimizer = keras.optimizers.Adam(learning_rate=0.5)
# Randomly select a subset of users
user_indices = np.arange(num_users)
selected_users = np.random.choice(user_indices, size=subset_users, replace=False)

# Split the selected users into training and test sets (80% train, 20% test)
train_users, test_users = train_test_split(selected_users, test_size=0.2, random_state=42)

# Select the corresponding data for the training and test sets
y_train = y[:, train_users]  
y_test = y[:, test_users]    

M_train = M[:, train_users]  
M_test = M[:, test_users]    

nm,nu = y_train.shape
print(nm,nu)

alpha = 0.01  # Reduce the learning rate to avoid divergence
iterations = 200
lam = 1

# Initialize features and weights with small random values instead of zeros
# initial_x = np.random.randn(y_train.shape[0], 10) * 0.1  # Small random values
# initial_w = np.random.randn(y_train.shape[1], 10) * 0 # Small random values
# initial_b = np.random.randn(y_train.shape[1]) * 0  # Small random values
# print(initial_x.shape,initial_w.shape,initial_b.shape)

tf.random.set_seed(1234) # for consistent results

w = tf.Variable(tf.random.normal((nu,  num_features),dtype=tf.float64),  name='w')
x = tf.Variable(tf.random.normal((nm, num_features),dtype=tf.float64),  name='x')
b = tf.Variable(tf.random.normal((1,          nu),   dtype=tf.float64),  name='b')

1682 754


In [34]:
w,b,x = gradientDecent(x,y_train,w,b,alpha,iterations,lam,M_train)

Training loss at iteration 0: 4730887.9
Training loss at iteration 20: 151020.2
Training loss at iteration 40: 36455.0
Training loss at iteration 60: 11851.4
Training loss at iteration 80: 6775.2
Training loss at iteration 100: 5503.0
Training loss at iteration 120: 5075.1
Training loss at iteration 140: 4883.2
Training loss at iteration 160: 4776.8
Training loss at iteration 180: 4709.4


In [35]:
print(x.shape,w.shape,b.shape)

(1682, 100) (754, 100) (1, 754)


In [36]:
y_pred = predict(x, w, b)
y_pred_masked = y_pred * M_train
y_masked = y_train * M_train
y_flat = y_masked[M_train > 0]
y_pred_flat = y_pred_masked[M_train > 0]
mse = mean_squared_error(y_flat, y_pred_flat)
rmse = np.sqrt(mse)
print(y_flat)
print(y_pred_flat)
print(r2_score(y_flat, y_pred_flat))
print(r2_score(y_masked, y_pred_masked))

(1682, 100) (754, 100) (1, 754)
[4. 5. 4. ... 4. 3. 3.]
[4.11597664 5.05895166 4.06278109 ... 3.98567781 2.99868701 3.01018467]
0.9939252525157379
0.9992213084937138


In [37]:
(1682, 100) (40, 100) (1, 40)
[4. 5. 4. ... 4. 3. 4.]
[3.99191436 4.80398109 3.99441594 ... 3.97959176 3.02567236 3.95175007]
0.9931301625618753
0.9988648010094924

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1329660725.py, line 2)

In [38]:
y_pred_test = predict(x, w, b)
y_pred_test.shape

(1682, 100) (754, 100) (1, 754)


(1682, 754)

In [39]:
# Fix learned movie features from training
X_fixed = x.numpy()  

# Initialize test users' parameters
w_test = tf.Variable(tf.random.normal((len(test_users), num_features), dtype=tf.float64), name='w_test')
b_test = tf.Variable(tf.random.normal((1, len(test_users)), dtype=tf.float64), name='b_test')
lam_test=10
# Optimize for test users
def test_loss_fn(X, W_test, B_test, Y_test, M_test, lam_test):
    residual = (tf.linalg.matmul(X, tf.transpose(W_test)) + B_test - Y_test) * M_test
    loss = 0.5 * tf.reduce_sum(residual ** 2) + (lam / 2) * tf.reduce_sum(W_test ** 2)
    return loss

optimizer = keras.optimizers.Adam(learning_rate=0.1)
for iter in range(200):  # Optimize for test users
    with tf.GradientTape() as tape:
        test_loss = test_loss_fn(X_fixed, w_test, b_test, y_test, M_test, lam)
    grads = tape.gradient(test_loss, [w_test, b_test])
    optimizer.apply_gradients(zip(grads, [w_test, b_test]))
    if iter % 20 == 0:
        print(f"Test Optimization Iteration {iter}: Loss {test_loss.numpy():.4f}")

# Predict ratings for test set after optimization
y_test_pred = np.matmul(X_fixed, np.transpose(w_test.numpy())) + b_test.numpy()

# Apply mask and evaluate
y_test_pred_masked = y_test_pred * M_test
y_test_flat = y_test[M_test > 0]
y_test_pred_flat = y_test_pred_masked[M_test > 0]

mse_test = mean_squared_error(y_test_flat, y_test_pred_flat)
rmse_test = np.sqrt(mse_test)
r2_test = r2_score(y_test_flat, y_test_pred_flat)
print(r2_score(y_test, y_test_pred_masked))
print(f"Test RMSE: {rmse_test:.4f}")
print(f"Test R^2 Score: {r2_test:.4f}")


Test Optimization Iteration 0: Loss 205156.6626
Test Optimization Iteration 20: Loss 26422.6467
Test Optimization Iteration 40: Loss 10388.3476
Test Optimization Iteration 60: Loss 6210.2161
Test Optimization Iteration 80: Loss 4777.4963
Test Optimization Iteration 100: Loss 4173.6386
Test Optimization Iteration 120: Loss 3888.3166
Test Optimization Iteration 140: Loss 3742.2867
Test Optimization Iteration 160: Loss 3662.6163
Test Optimization Iteration 180: Loss 3617.1098
0.9857757554600043
Test RMSE: 0.5493
Test R^2 Score: 0.7468
